#include "/Engine/Private/Common.ush"

//--------------------------------------------------------------------------------------
// Buffers
//--------------------------------------------------------------------------------------
RWStructuredBuffer<float3> Positions;         // VertexBuffer of the Mesh
// uniform int NumIndices;

[numthreads(16, 1, 1)]
void PositionUpdate(uint3 ThreadId : SV_DispatchThreadID)
{
	uint NumOfPositions, Stride;
	Positions.GetDimensions(NumOfPositions, Stride);
	// Z += 1
	if (ThreadId.x < NumOfPositions)
	{
		Positions[ThreadId.x][2] += 1;
	}
}