#pragma once
#include </Engine/Public/Platform.ush>

// local forces cache, three forces on the processed triangle

RWStructuredBuffer<float3> OutVec;
StructuredBuffer<float3> InVec;

[numthreads(16, 1, 1)]
void CopyVec(uint3 ThreadId : SV_DispatchThreadID)
{
	uint NumOfVertices, _;
	OutVec.GetDimensions(NumOfVertices, _);

	int Index = ThreadId.x;
	if (121 <= Index) return;
	
	OutVec[Index] = InVec[Index];
}